// 酒道数据
const wineData = [
    {
        name: '贵州茅台',
        type: '酱香型白酒',
        origin: '贵州茅台镇',
        alcohol: '53%vol',
        appearance: '无色透明，微黄',
        aroma: '酱香突出，幽雅细腻',
        taste: '醇厚丰满，回味悠长，空杯留香',
        price: '1499元/瓶（飞天53度500ml）',
        rating: '⭐⭐⭐⭐⭐',
        drinking: { temperature: '常温', vessel: '小酒杯', method: '小口慢品，先闻后饮' },
        pairing: ['酱牛肉', '花生米', '卤味', '清淡菜肴'],
        history: '始于1951年，由三家烧坊合并而成，是中国国酒代表。',
        tips: ['不宜冰镇', '开瓶后尽快饮用', '存放于阴凉处'],
        healthNote: '适量饮用，每次不超过50ml'
    },
    {
        name: '五粮液',
        type: '浓香型白酒',
        origin: '四川宜宾',
        alcohol: '52%vol',
        appearance: '清澈透明',
        aroma: '窖香浓郁，香气协调',
        taste: '绵甜甘冽，香味谐调，尾净余长',
        price: '1099元/瓶（普五52度500ml）',
        rating: '⭐⭐⭐⭐⭐',
        drinking: { temperature: '常温或微温', vessel: '白酒杯', method: '细品慢饮' },
        pairing: ['川菜', '火锅', '烧烤', '卤菜'],
        history: '源于明代，以五种粮食酿造，故名五粮液。',
        tips: ['适合搭配重口味菜肴', '存放避光', '开瓶后密封保存'],
        healthNote: '适量饮用，每次不超过50ml'
    },
    {
        name: '山西汾酒',
        type: '清香型白酒',
        origin: '山西杏花村',
        alcohol: '53%vol',
        appearance: '无色清亮',
        aroma: '清香纯正，余香悠长',
        taste: '绵柔爽净，回味怡畅',
        price: '158元/瓶（青花20年500ml）',
        rating: '⭐⭐⭐⭐',
        drinking: { temperature: '常温', vessel: '小酒盅', method: '一口闷或小口品' },
        pairing: ['面食', '羊肉', '凉菜', '清淡菜肴'],
        history: '汾酒有6000年历史，是中国最古老的白酒之一。',
        tips: ['清香型适合初饮者', '可作为调酒基酒', '性价比高'],
        healthNote: '适量饮用，每次不超过100ml'
    },
    {
        name: '拉菲红酒',
        type: '干红葡萄酒',
        origin: '法国波尔多',
        alcohol: '13%vol',
        appearance: '深宝石红色',
        aroma: '黑醋栗、雪松、烟熏香',
        taste: '单宁细腻，结构优雅，余味悠长',
        price: '3000-50000元/瓶',
        rating: '⭐⭐⭐⭐⭐',
        drinking: { temperature: '16-18°C', vessel: '波尔多杯', method: '醒酒1-2小时后饮用' },
        pairing: ['牛排', '羊排', '鹅肝', '硬质奶酪'],
        history: '拉菲酒庄建于1234年，1855年被评为一级庄。',
        tips: ['需要醒酒', '横放储存', '避光恒温保存'],
        healthNote: '每日不超过150ml'
    },
    {
        name: '青岛啤酒',
        type: '淡色拉格啤酒',
        origin: '山东青岛',
        alcohol: '4.3%vol',
        appearance: '金黄透亮，泡沫洁白',
        aroma: '麦芽香与酒花香平衡',
        taste: '清爽顺滑，苦味适中',
        price: '5-10元/瓶',
        rating: '⭐⭐⭐⭐',
        drinking: { temperature: '8-10°C', vessel: '啤酒杯', method: '大口畅饮' },
        pairing: ['海鲜', '烧烤', '炸鸡', '小龙虾'],
        history: '1903年由德国人创建，是中国最早的啤酒品牌之一。',
        tips: ['冰镇后口感更佳', '开瓶后尽快饮用', '夏季消暑佳品'],
        healthNote: '每日不超过500ml'
    },
    {
        name: '獭祭清酒',
        type: '纯米大吟酿',
        origin: '日本山口县',
        alcohol: '16%vol',
        appearance: '清澈透明',
        aroma: '果香馥郁，有蜜瓜香',
        taste: '入口顺滑，甘甜清爽',
        price: '300-800元/瓶（720ml）',
        rating: '⭐⭐⭐⭐⭐',
        drinking: { temperature: '5-15°C', vessel: '清酒杯', method: '冷饮或常温' },
        pairing: ['刺身', '寿司', '天妇罗', '清淡日料'],
        history: '旭酒造创立于1948年，獭祭是其代表作。',
        tips: ['开瓶后冷藏保存', '二三割三分精米步合最佳', '适合清酒入门'],
        healthNote: '每日不超过180ml'
    },
    {
        name: '轩尼诗XO',
        type: '干邑白兰地',
        origin: '法国干邑',
        alcohol: '40%vol',
        appearance: '琥珀色，晶莹剔透',
        aroma: '果脯、香料、橡木香',
        taste: '醇厚圆润，层次丰富',
        price: '1200-1500元/瓶（700ml）',
        rating: '⭐⭐⭐⭐⭐',
        drinking: { temperature: '常温', vessel: '白兰地杯', method: '手心温杯，慢慢品味' },
        pairing: ['雪茄', '巧克力', '坚果', '甜点'],
        history: '轩尼诗创立于1765年，XO是其经典之作。',
        tips: ['用手温杯释放香气', '可加冰或纯饮', '适合餐后饮用'],
        healthNote: '每日不超过30ml'
    },
    {
        name: '山崎威士忌',
        type: '单一麦芽威士忌',
        origin: '日本大阪',
        alcohol: '43%vol',
        appearance: '金黄琥珀色',
        aroma: '花果香、蜂蜜、橡木',
        taste: '柔和顺滑，余味甘甜',
        price: '500-5000元/瓶',
        rating: '⭐⭐⭐⭐⭐',
        drinking: { temperature: '常温或加冰', vessel: '威士忌杯', method: '纯饮、加冰或水割' },
        pairing: ['烟熏三文鱼', '黑巧克力', '坚果', '奶酪'],
        history: '山崎蒸馏所建于1923年，是日本第一家威士忌蒸馏所。',
        tips: ['12年款性价比高', '18年款更醇厚', '可尝试水割喝法'],
        healthNote: '每日不超过50ml'
    }
];
